services:

  postgres:
    image: postgres
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8032:8032
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin-pgpass.txt:/pgadmin-pgpass.txt:ro
    environment:
      PGADMIN_LISTEN_PORT: 8032
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_DEFAULT_SERVER_PORT: 5432
