services:

  postgres:
    image: postgres
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8032:8032
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin-pgpass.txt:/pgadmin-pgpass.txt:ro
    environment:
      PGADMIN_LISTEN_PORT: 8032
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_DEFAULT_SERVER_PORT: 5432

  percona:
    image: percona:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: percona

  phpmyadmin:
    depends_on: [ percona ]
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80 # http://localhost:8080
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: percona
      PMA_USER: root
      PMA_PASSWORD: percona

  sysbench:
    image: tjcelaya/sysbench
    build:
      dockerfile: sysbench.Dockerfile
